#!/bin/zsh
name=$1
option=$2
if [ -z "${name}" ] || [ -z "$option}" ]
then
  echo "Usage: newlatex [name] [option]. Option 1 for everything new; option 2 for one new tex file."
else
  case $option in
    1)
      cp ~/LaTexStyle/* ./
      mv newfile.tex "${name}"
      ;;
    2)
      cp ~/LaTexStyle/newfile.tex "${name}"
      ;;
  esac
fi
