#!/bin/zsh
name=$1
option=$2
if [ -z "${name}" ] || [ -z "$option}" ]
then
  echo "Usage: newlatex [name] [option]. Option 1 for everything new; option 2 for one new tex file."
else
  case $option in
    1)
      cp ~/lib/LaTexStyle/* ./
      mv newfile.tex "${name}.tex"
      ;;
    2)
      cp ~/lib/LaTexStyle/newfile.tex "${name}.tex"
      cp ~/lib/LaTexStyle/newfile-printfriendly.tex "${name}-printfriendly.tex"
      cp ~/lib/LaTexStyle/newfile-tablet.tex "${name}-tablet.tex"
      cp ~/lib/LaTexStyle/newfile-publish.tex "${name}-publish.tex"
      ;;
  esac
fi
